version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: onlineshopping
      POSTGRES_DB: onlineshop
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data   # <== FIXED
    networks:
      - mynetwork


  app:
    build: .
    container_name: springboot_app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/onlineshop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: onlineshopping
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ../../webappOnly/public:/public
      - ./logs:/app/logs
    networks:
      - mynetwork

volumes:
  postgres_data:
    name: postgres_data

networks:
  mynetwork:
    driver: bridge
