package com.user.utility;

public enum ReturnStatus {

	REQUESTED, APPROVED, REJECTED, PICKUP_SCHEDULED, PICKED_UP, RECEIVED_AT_WAREHOUSE, QC_PENDING, QC_PASSED, QC_FAILED,
	REFUND_INITIATED, REFUNDED, COMPLETED

}
